  CREATE TABLE "SAMPLE"."VENDOR" 
   ("VENDORID" NUMBER NOT NULL ENABLE, 
	"VENDORNAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "VENDOR_PK" PRIMARY KEY ("VENDORID")
   );


  CREATE SEQUENCE  "SAMPLE"."VENDOR_SEQ" 
  INCREMENT BY 1 
  START WITH 1
  nomaxvalue;
  /

  CREATE OR REPLACE EDITIONABLE TRIGGER "SAMPLE"."VENDOR_TRIGGER" 
BEFORE INSERT ON VENDOR 
FOR EACH ROW
BEGIN
  SELECT VENDOR_SEQ.NEXTVAL INTO :NEW.VENDORID FROM DUAL;
END;
/
ALTER TRIGGER "SAMPLE"."VENDOR_TRIGGER" ENABLE;
