<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../JMSQueueConsumer.wsdl"/>
      <rootElement name="ocrInvoice" namespace="http://www.iconpln.co.id/procure-to-pay"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../ocrInvoiceProcess.wsdl"/>
      <rootElement name="invoice" namespace="http://www.iconpln.co.id/procure-to-pay"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [TUE FEB 04 19:50:11 ICT 2020]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:client="http://xmlns.oracle.com/ocrInvoiceValidator/ocrInvoiceValidator/ocrInvoiceProcess"
                xmlns:imp1="http://www.iconpln.co.id/procure-to-pay"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/ocrInvoiceValidator/ocrInvoiceValidator/JMSQueueConsumer"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsl xsi imp1 xsd plt pc wsdl jca tns client plnk oraext socket ora bpws xdk ids mhdr bpm xp20 hwf xref dvm med bpel ldap">
  <xsl:template match="/">
    <imp1:invoice>
      <imp1:invoiceData>
        <imp1:invoiceDate>
          <xsl:value-of select="/imp1:ocrInvoice/imp1:invoiceData/imp1:invoiceDate"/>
        </imp1:invoiceDate>
        <imp1:invoiceNumber>
          <xsl:value-of select="/imp1:ocrInvoice/imp1:invoiceData/imp1:invoiceNumber"/>
        </imp1:invoiceNumber>
        <imp1:invoiceCurrency>
          <xsl:value-of select="/imp1:ocrInvoice/imp1:invoiceData/imp1:invoiceCurrency"/>
        </imp1:invoiceCurrency>
        <imp1:customerReference>
          <xsl:value-of select="/imp1:ocrInvoice/imp1:invoiceData/imp1:customerReference"/>
        </imp1:customerReference>
        <imp1:chargedAmount>
          <xsl:value-of select="/imp1:ocrInvoice/imp1:invoiceData/imp1:chargedAmount"/>
        </imp1:chargedAmount>
        <imp1:linkToInvoiceScanImage>
          <xsl:value-of select="/imp1:ocrInvoice/imp1:invoiceData/imp1:linkToInvoiceScanImage"/>
        </imp1:linkToInvoiceScanImage>
        <imp1:custoemrNumber>
          <xsl:value-of select="/imp1:ocrInvoice/imp1:invoiceData/imp1:custoemrNumber"/>
        </imp1:custoemrNumber>
      </imp1:invoiceData>
      <imp1:billTo>
        <imp1:name>
          <xsl:value-of select="/imp1:ocrInvoice/imp1:billTo/imp1:name"/>
        </imp1:name>
        <imp1:contact>
          <xsl:value-of select="/imp1:ocrInvoice/imp1:billTo/imp1:contact"/>
        </imp1:contact>
        <imp1:contractid>
          <xsl:value-of select="/imp1:ocrInvoice/imp1:billTo/imp1:contractid"/>
        </imp1:contractid>
      </imp1:billTo>
      <imp1:vendor>
        <imp1:name>
          <xsl:value-of select="/imp1:ocrInvoice/imp1:vendor/imp1:name"/>
        </imp1:name>
        <imp1:contact>
          <xsl:value-of select="/imp1:ocrInvoice/imp1:vendor/imp1:contact"/>
        </imp1:contact>
      </imp1:vendor>
      <imp1:lineItems>
        <imp1:line>
          <xsl:value-of select="/imp1:ocrInvoice/imp1:lineItems/imp1:line"/>
        </imp1:line>
      </imp1:lineItems>
      <imp1:remitTo>
        <imp1:IBAN>
          <xsl:value-of select="/imp1:ocrInvoice/imp1:remitTo/imp1:IBAN"/>
        </imp1:IBAN>
        <imp1:accountNumber>
          <xsl:value-of select="/imp1:ocrInvoice/imp1:remitTo/imp1:accountNumber"/>
        </imp1:accountNumber>
        <imp1:SWFT>
          <xsl:value-of select="/imp1:ocrInvoice/imp1:remitTo/imp1:SWFT"/>
        </imp1:SWFT>
      </imp1:remitTo>
    </imp1:invoice>
  </xsl:template>
</xsl:stylesheet>
