<?binding.jca partnerMgmtSvc_db.jca?>
<wsdl:definitions name="partnerMgmtSvc" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ocrInvoiceValidator/ocrInvoiceValidator/partnerMgmtSvc" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/partnerMgmtSvc" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ocrInvoiceValidator/ocrInvoiceValidator/partnerMgmtSvc" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="partnerMgmtSvc_plt">
        <plt:role name="partnerMgmtSvc_role">
            <plt:portType name="tns:partnerMgmtSvc_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/partnerMgmtSvc" schemaLocation="xsd/partnerMgmtSvc_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="partnerMgmtSvcSelect_inputParameters">
        <wsdl:part name="partnerMgmtSvcSelect_inputParameters" element="top:partnerMgmtSvcSelect_pContractNumberInputParameters"/>
    </wsdl:message>
    <wsdl:message name="ContractCollection_msg">
        <wsdl:part name="ContractCollection" element="top:ContractCollection"/>
    </wsdl:message>
    <wsdl:portType name="partnerMgmtSvc_ptt">
        <wsdl:operation name="partnerMgmtSvcSelect">
            <wsdl:input message="tns:partnerMgmtSvcSelect_inputParameters"/>
            <wsdl:output message="tns:ContractCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
